apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: ${NAMESPACE}
data:
  # Backend settings
  BACKEND_PORT: "3001"
  LOG_LEVEL: "debug"  # e.g., debug, info
  # Frontend settings (e.g., API base URL)
  REACT_APP_API_URL: "http://backend-service.${NAMESPACE}.svc.cluster.local:3001"  # Internal service URL
  # Add more as needed, e.g., DB_URL if using a database

